FROM python:3.11.4-alpine

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

RUN pip install fastapi uvicorn python-multipart

WORKDIR /app
COPY main.py /app/main.py
COPY mercari.sqlite3 /app/mercari.sqlite3

USER trainee

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
